fix filter

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -21,12 +21,18 @@ jobs:
         with:
           java-version: '21'
           distribution: 'temurin'
-      - name: Check README
+      - name: Check Version
         run: |
           if grep -q "id(\"io.github.klahap.fraplin\") version \"$GITHUB_REF_NAME\"" README.md; then
-            echo "README is valid"
+            echo "README version is valid"
           else
             echo "Error, update plugin version in README.md"
+            exit 1
+          fi
+          if grep -q "version = \"$GITHUB_REF_NAME\"" build.gradle.kts; then
+            echo "plugin version is valid"
+          else
+            echo "Error, update plugin version in build.gradle.kts"
             exit 1
           fi
       - name: publish
